name: 'Deploy Logic App Workflows'

on:
  push:
    paths:
      - "logic/**"
      - "function/**"
      - ".github/workflows/workflow_deploy.yml"

jobs:
  job_deploy_logic_app_workflows:
    name: LogicAppWorkflows
    needs: deploy_core_infrastructure
    runs-on: windows-latest
    steps:
      - name: 'Setup agent'
        shell: pwsh
        run: |
          # Grouping task logs
          Write-Output "::group::Setup agent"

          Install-Module -Name Az.Functions -MinimumVersion "4.0.0" -Force

          Write-Output "::endgroup::"
      
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: /logic/
          dest: ${{ github.workspace }}/wflows.zip

      - uses: actions/upload-artifact@v1
        with:
          name: workflows
          path: ${{ github.workspace }}/wflows.zip

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true
          
      - name: Get publish Profile
        id: publishprofile
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $profile = Get-AzWebAppPublishingProfile `
                -ResourceGroupName ${{ env.resource_group_name }}" `
                -Name ${{ env.logic_app_name }}
            $profile = $profile.Replace("`r", "").Replace("`n", "")
            Write-Output "::set-output name=profile::$profile"
          azPSVersion: latest

      - name: Deploy to Azure Logic App
        uses: azure/functions-action@v1.3.1
        id: la
        with:
          app-name: ${{ env.resource_group_name }}"
          package: './wflows.zip'
          publish-profile: ${{steps.publishprofile.outputs.profile}}

      - name: Swap parameter files 
        id: params
        uses: azure/powershell@v1
        with:
          inlineScript: |
            az functionapp deploy --resource-group ${{ env.resource_group_name }}" --name ${{ env.logic_app_name }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
          azPSVersion: latest