name: 'Deploy Logic App Workflows'
description: 'Deploys the /logic directory onto the single tenant logic app'

inputs:
  logicAppName:
    description: 'Name of the single-tenant logic app'
    required: true
  resourceGroupName:
    description: 'Name of the resource group'
    required: true


runs:
  using: 'composite'
  steps:
    - name: 'Setup agent'
      shell: pwsh
      run: |
        # Grouping task logs
        Write-Output "::group::Setup agent"

        Install-Module -Name Az.Function -MinimumVersion "1.10.0" -Force

        Write-Output "::endgroup::"
    
    - name: Checkout
      uses: actions/checkout@v1    
    
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
    
    - uses: actions/download-artifact@master
      with:
        name: logic
        path: ./output/
        
    - name: Get publish Profile
      id: publishprofile
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $profile = Get-AzWebAppPublishingProfile `
              -ResourceGroupName ${{ inputs.resourceGroupName }} `
              -Name ${{ inputs.logicAppName }}
          $profile = $profile.Replace("`r", "").Replace("`n", "")
          Write-Output "::set-output name=profile::$profile"
        azPSVersion: latest

    - name: Deploy to Azure Logic App
      uses: Azure/functions-action@v1.3.1
      id: la
      with:
        app-name: ${{inputs.resourceGroupName}}
        package: './output/logic.zip'
        publish-profile: ${{steps.publishprofile.outputs.profile}}

    - name: Swap parameter files 
      id: params
      uses: azure/powershell@v1
      with:
        inlineScript: |
          az functionapp deploy --resource-group ${{ inputs.resourceGroupName }} --name ${{ inputs.logicAppName }} --src-path  logic/azure.parameters.json --type static --target-path parameters.json
        azPSVersion: latest
